name: E5

on: 
  workflow_dispatch:
  schedule:
    - cron:  '0/57 9-16 * * *'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event.repository.owner.id == github.event.sender.id) || ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: Build and call API
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: true 
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        check-latest: true
    - name: Install requests 
      run: |
        pip install requests
    - name: Read config from secrets  
      env: 
        CONFIG_ID: ${{ secrets.CONFIG_ID }} 
        CONFIG_KEY: ${{ secrets.CONFIG_KEY }} 
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }} 
      run: | 
        cp main.py temp.py
        echo -e "client_id=\"$CONFIG_ID\"" > configid.txt
        echo -e "client_secret=\"$CONFIG_KEY\"" > configkey.txt
        echo -e "refresh_token=\"$REFRESH_TOKEN\"" > refreshtoken.txt
        sed -i '10 r configid.txt' temp.py
        sed -i '12 r configkey.txt' temp.py
        sed -i '14 r refreshtoken.txt' temp.py
        echo ${{secrets.CONFIG_ID}} | sed 's/./& /g'
    - name: Test Api
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python3 temp.py
    - name: Delete secrets config
      run: | 
        rm -f temp.py
        rm -f configid.txt
        rm -f configkey.txt
        rm -f refreshtoken.txt
        rm -f Secret.txt
    - name: Commit
      run: |
        git config --global user.email "125961492+devolart@users.noreply.github.com"
        git config --global user.name "devolart"
        git add .
        git commit -m "E5" -a
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
